# Generated by Django 3.2.4 on 2021-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
