# Generated by Django 3.2.4 on 2021-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
